pythonic/lessons/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from flask_login import current_user
from pythonic.models import  Course
from wtforms import StringField, SubmitField
from wtforms_sqlalchemy.fields import QuerySelectField
from flask_ckeditor import CKEditorField
from wtforms.validators import (
    DataRequired,
    Length
)

def choice_query():
    return Course.query


class NewLessonForm(FlaskForm):
    course = QuerySelectField("Course", query_factory=choice_query, get_label="title")
    title = StringField("Lesson Title", validators=[DataRequired(), Length(max=100)])
    slug = StringField(
        "Slug",
        validators=[DataRequired(), Length(max=32)],
        render_kw={
            "placeholder": "Descriptive short version of your title. SEO friendly"
        },
    )
    content = CKEditorField(
        "Lesson Content", validators=[DataRequired()], render_kw={"rows": "20"}
    )
    thumbnail = FileField(
        "Thumbnail", validators=[DataRequired(), FileAllowed(["jpg", "png"])]
    )
    submit = SubmitField("Post")

class LessonUpdateForm(NewLessonForm):
    thumbnail = FileField("Thumbnail", validators=[FileAllowed(["jpg", "png"])])
    submit = SubmitField("Update")

pythonic/courses/routes.py
from flask import Blueprint
from pythonic.models import Lesson, Course
from flask import render_template,request


courses_bp = Blueprint("courses_bp", __name__)

@courses_bp.route("/<string:course_title>")
def course(course_title):
    course = Course.query.filter_by(title=course_title).first()
    course_id = course.id if course else None
    course = Course.query.get_or_404(course_id)
    page = request.args.get("page", 1, type=int)
    lessons = Lesson.query.filter_by(course_id=course_id).paginate(
        page=page, per_page=6
    )
    return render_template("course.html", title=course_title, course=course, lessons=lessons)

@courses_bp.route('/courses')
def courses():  
    page = request.args.get("page", 1, type=int)
    courses = Course.query.paginate(page=page, per_page=5)
    return render_template('courses.html', courses=courses)

pythonic/lessons/routes.py
from flask import Blueprint
from pythonic.models import  Lesson, Course
from flask import render_template, url_for, flash, redirect, request, session, abort
from pythonic.lessons.forms import (
    NewLessonForm,
    LessonUpdateForm
)
from pythonic.courses.forms import NewCourseForm
from pythonic import bcrypt, db
from flask import current_app
from flask_modals import render_template_modal
from flask_login import (
    login_required,
    current_user,
    login_required,
)
from pythonic.helpers import save_picture
from pythonic.lessons.helpers import get_previous_next_lesson, delete_picture


lessons = Blueprint("lessons", __name__)

@lessons.route("/dashboard/new_lesson", methods=["GET", "POST"])
@login_required
def new_lesson():
    new_lesson_form = NewLessonForm()
    new_course_form = NewCourseForm()
    form = ""
    flag = session.pop("flag", False)
    if "content" in request.form:
        form = "new_lesson_form"
    elif "description" in request.form:
        form = "new_course_form"

    if form == "new_lesson_form" and new_lesson_form.validate_on_submit():
        if new_lesson_form.thumbnail.data:
            picture_file = save_picture(
                new_lesson_form.thumbnail.data, "static/lesson_thumbnails"
            )
        lesson_slug = str(new_lesson_form.slug.data).replace(" ", "-")
        course = new_lesson_form.course.data
        lesson = Lesson(
            title=new_lesson_form.title.data,
            content=new_lesson_form.content.data,
            slug=lesson_slug,
            author=current_user,
            course_name=course,
            thumbnail=picture_file,
        )
        db.session.add(lesson)
        db.session.commit()
        flash("Your lesson has been created!", "success")
        return redirect(url_for("lessons.new_lesson"))

    elif form == "new_course_form" and new_course_form.validate_on_submit():
        if new_course_form.icon.data:  
            picture_file = save_picture(
                new_course_form.icon.data, "static/course_icons",output_size=(150,150)
            )
        course_title = str(new_course_form.title.data).replace(" ", "-")
        course = Course(
            title=course_title,
            description=new_course_form.description.data,
            icon=picture_file,
        )
        db.session.add(course)
        db.session.commit()
        session["flag"] = True
        flash("New Course has been created!", "success")
        return redirect(url_for("users.dashboard"))

    modal = None if flag else "newCourse"
    return render_template_modal(
        "new_lesson.html",
        title="New Lesson",
        new_lesson_form=new_lesson_form,
        new_course_form=new_course_form,
        active_tab="new_lesson",
        modal=modal,
    )

@lessons.route("/<string:course>/<string:lesson_slug>")
def lesson( lesson_slug,course):
    lesson = Lesson.query.filter_by(slug=lesson_slug).first()
    if lesson:
        previous_lesson, next_lesson = get_previous_next_lesson(lesson)
    lesson_id = lesson.id if lesson else None
    lesson = Lesson.query.get_or_404(lesson_id)
    return render_template("lesson_view.html", title=lesson.title, lesson=lesson, previous_lesson=previous_lesson, next_lesson=next_lesson)

@lessons.route("/dashboard/user_lessons", methods=["GET", "POST"])
@login_required
def user_lessons():
    return render_template(
        "user_lessons.html", title="Your Lessons", active_tab="user_lessons"
    )

@lessons.route("/<string:course>/<string:lesson_slug>/update", methods=["GET", "POST"])
def update_lesson(lesson_slug, course):
    lesson = Lesson.query.filter_by(slug=lesson_slug).first()
    if lesson:
        previous_lesson, next_lesson = get_previous_next_lesson(lesson)
    lesson_id = lesson.id if lesson else None
    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403)
    form = LessonUpdateForm()
    if form.validate_on_submit():
        lesson.course_name = form.course.data
        lesson.title = form.title.data
        lesson.slug = str(form.slug.data).replace(" ", "-")
        lesson.content = form.content.data
        if form.thumbnail.data:
            delete_picture(lesson.thumbnail, "static/lesson_thumbnails")
            new_picture = save_picture(form.thumbnail.data, "static/lesson_thumbnails")
            lesson.thumbnail = new_picture
        db.session.commit()
        flash("Your lesson has been updated!", "success")
        return redirect(
            url_for("lessons.lesson", lesson_slug=lesson.slug, course=lesson.course_name.title)
        )
    elif request.method == "GET":
        form.course.data = lesson.course_name.title
        form.title.data = lesson.title
        form.slug.data = lesson.slug
        form.content.data = lesson.content
    return render_template(
        "update_lesson.html",
        title="Update | " + lesson.title,
        lesson=lesson,
        previous_lesson=previous_lesson,
        next_lesson=next_lesson,
        form=form,
    )

@lessons.route("/lesson/<lesson_id>/delete", methods=["POST"])
def delete_lesson(lesson_id):
    lesson = Lesson.query.get_or_404(lesson_id)
    if lesson.author != current_user:
        abort(403)
    db.session.delete(lesson)
    db.session.commit()
    flash("Your lesson has been deleted!", "success")
    return redirect(url_for("lessons.user_lessons"))

pythonic/main/routes.py
from flask import Blueprint
from pythonic.models import  Lesson, Course
from flask import render_template

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
    lessons = Lesson.query.order_by(Lesson.date_posted.desc()).paginate(page=1, per_page=6) 
    courses = Course.query.paginate(page=1, per_page=3)
    return render_template("home.html", lessons=lessons, courses=courses)


@main.route("/about")
def about():
    return render_template("about.html", title="About")

pythonic/users/routes.py
from flask import Blueprint
from pythonic.models import User, Lesson, Course
from flask import render_template, url_for, flash, redirect, request, session, abort
from pythonic.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateProfileForm,
)
from pythonic import bcrypt, db
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user,
    login_required,
)
from pythonic.helpers import save_picture


users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("users.home"))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            fname=form.fname.data,
            lname=form.lname.data,
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
        )
        db.session.add(user)
        db.session.commit()
        flash(f"Account created successfully for {form.username.data}", "success")
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("users.home"))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get("next")
            flash("You have been logged in!", "success")
            return redirect(next_page) if next_page else redirect(url_for("users.home"))
        else:
            flash("Login Unsuccessful. Please check credentials", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("users.home"))


@users.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    return render_template("dashboard.html", title="Dashboard", active_tab=None)


@users.route("/dashboard/profile", methods=["GET", "POST"])
@login_required
def profile():
    profile_form = UpdateProfileForm()
    if profile_form.validate_on_submit():
        if profile_form.picture.data:
            picture_file = save_picture(profile_form.picture.data, "static/user_pics",output_size=(150,150))
            current_user.image_file = picture_file
        current_user.username = profile_form.username.data
        current_user.email = profile_form.email.data
        current_user.bio = profile_form.bio.data
        db.session.commit()
        flash("Your profile has been updated", "success")
        return redirect(url_for("users.profile"))
    elif request.method == "GET":
        profile_form.username.data = current_user.username
        profile_form.email.data = current_user.email
        profile_form.bio.data = current_user.bio
    image_file = url_for("static", filename=f"user_pics/{current_user.image_file}")
    return render_template(
        "profile.html",
        title="Profile",
        profile_form=profile_form,
        image_file=image_file,
        active_tab="profile",
    )

@users.route("/author/<string:username>", methods=["GET"])
def author(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get("page", 1, type=int)
    lessons = (
        Lesson.query.filter_by(author=user)
        .order_by(Lesson.date_posted.desc())
        .paginate(page=1, per_page=6)
    )
    return render_template(
        "author.html", title=f"{user.username}'s Lessons", user=user, lessons=lessons
    )   

pythonic/templates/author.html
{% extends "layout.html"%} {% block content %}
<!-- author image and bio -->
<div class="container-fluid bg-secondary">
  <div class="container">
    <div class="row p-5">
      <div class="col-6">
        <img
          class="rounded-circle"
          src="{{url_for('static', filename='user_pics/' + user.image_file)}}"
          alt=""
        />
      </div>
      <div class="col-6">
        <span class="lead text-light">{{user.bio}}</span>
      </div>
    </div>
  </div>
</div>
<section class="bg-light">
  <div class="container p-5">
    <div class="row mb-5"></div>
    <div class="row">
      {% for lesson in lessons.items %}
      <div class="col-sm-12 col-md-6 col-lg-4 pb-5 d-flex align-items-stretch">
        <div class="card lesson">
          <img
            src="{{url_for('static', filename='lesson_thumbnails/'+lesson.thumbnail)}}"
            class="card-img"
          />
          <div class="card-body d-flex flex-column">
            <h5 class="card-title">
              <a
                class="text-decoration-none text-dark"
                href="{{url_for('lessons.lesson', lesson_slug=lesson.slug, course=lesson.course_name.title)}}"
                >{{lesson.title}}</a
              >
            </h5>
            <p class="card-text mb-0">
              In:
              <a
                href="{{url_for('courses_bp.course', course_title=lesson.course_name.title)}}"
                class="link"
                >{{lesson.course_name.title}}</a
              >
            </p>
            <span class="text-muted"
              >On: {{lesson.date_posted.strftime('%Y-%m-%d')}}</span
            >
          </div>
        </div>
      </div>
      {% endfor %}

      <!-- pagination links -->
      <nav class="mt-5" aria-label="...">
        <ul class="pagination" style="display: flex; justify-content: flex-end">
          {% for page_num in lessons.iter_pages(left_edge=1, right_edge=1,
          left_current=1, right_current=2) %} {% if page_num %} {% if
          lessons.page == page_num %}
          <li class="page-item active">
            <a
              href="{{url_for('users.author', username=user.username, page=page_num)}}"
              class="page-link"
              >{{page_num}}</a
            >
          </li>
          {%else%}
          <li class="page-item">
            <a
              href="{{url_for('users.author', username=user.username, page=page_num)}}"
              class="page-link"
              >{{page_num}}</a
            >
          </li>
          {%endif%} {% else %}
          <span class="mx-2">...</span>
          {% endif %} {% endfor %}
        </ul>
      </nav>
    </div>
  </div>
</section>

{% endblock content%}

pythonic/templates/courses.html
{% extends "layout.html"%} {% block content %}

<section class="bg-ligh">
  <div class="container p-5">
    <h3 class="text-center text-secondary" id="learn">Courses</h3>
    <div class="row">
      {% for course in courses.items %}
      <div class="col-sm-12 col-md-6 col-lg-4 p-3 d-flex align-items-stretch">
        <a
          href="{{url_for('courses_bp.course', course_title=course.title)}}"
          class="text-decoration-none"
        >
          <div class="card bg-dark text-light h-100">
            <div class="card-body text-center">
              <img
                src="{{url_for('static', filename='course_icons/'+course.icon)}}"
                alt=""
                class="card-img w-25"
              />
              <h4 class="card-title mb-3">{{course.title}}</h4>
              <p class="card-text">{{course.description}}</p>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
      <!-- pagination links -->
      <nav class="mt-5" aria-label="...">
        <ul class="pagination" style="display: flex; justify-content: flex-end">
          {% for page_num in courses.iter_pages(left_edge=1, right_edge=1,
          left_current=1, right_current=2) %} {% if page_num %} {% if
          courses.page == page_num %}
          <li class="page-item active">
            <a href="{{url_for('courses_bp.courses', page=page_num)}}" class="page-link"
              >{{page_num}}</a
            >
          </li>
          {%else%}
          <li class="page-item">
            <a href="{{url_for('courses_bp.courses', page=page_num)}}" class="page-link"
              >{{page_num}}</a
            >
          </li>
          {%endif%} {% else %} ... {% endif %} {% endfor %}
        </ul>
      </nav>
    </div>
  </div>
</section>

{% endblock content %}

pythonic/templates/home.html
{%extends "layout.html"%} {%block content%}
<section
  class="text-light p-5 p-lg-0 pt-lg-5 text-center text-sm-start bg-light"
>
  <div class="container">
    <div class="d-sm-flex align-items-center justify-content-between p-5">
      <div>
        <h1 class="mb-10 text-dark">
          Learn <span class="text-warning"> To Code</span>
        </h1>
        <p class="lead my-4 text-dark">
          We focus on teaching programming in an intuitive and easy to follow
          way. All you need is dedication!
        </p>
        <a
          class="btn btn-danger btn-lg border"
          href="https://www.youtube.com/channel/UCEsvQ6d7qsnOSNXtccIzScQ?sub_confirmation=1"
          target="_blank"
        >
          <i class="bi bi-youtube m-3"></i>Subscribe
        </a>
      </div>
      <img
        class="img-fluid w-50 d-none d-sm-block"
        src="{{url_for('static', filename='showcase.svg')}}"
        alt=""
      />
    </div>
  </div>
</section>
<!-- Social Media -->
<section class="bg-primary text-light p-5">
  <div class="container">
    <div class="d-md-flex justify-content-between align-items-center">
      <h3 class="mb-3 text-center">Join Our Community</h3>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <button
          class="navbar-toggler border"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#socialbtn"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="socialbtn">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a
                class="btn btn-dark ms-5 button_width"
                href="https://github.com/omar-ghoneim"
                target="_blank"
              >
                <i class="bi-github" role="img"></i>
                GitHub
              </a>
            </li>
            <li>
              <a
                class="btn btn-dark ms-5 button_width"
                href="https://www.facebook.com/Pythonic88"
                target="_blank"
              >
                <i class="bi bi-facebook"></i>
                Facebook
              </a>
            </li>
            <li class="nav-item">
              <a
                type="button"
                class="btn btn-dark ms-5 button_width"
                href="https://www.instagram.com/pythonic_88"
                target="_blank"
              >
                <i class="bi bi-instagram"></i>
                Instagram
              </a>
            </li>
            <li class="nav-item">
              <a
                class="btn btn-dark ms-5 button_width"
                href="https://twitter.com/Pythonic88"
                target="_blank"
              >
                <i class="bi bi-twitter"></i>
                Twitter
              </a>
            </li>
            <li class="nav-item">
              <a
                class="btn btn-dark ms-5 button_width"
                href="https://www.tiktok.com/@pythonic88"
                target="_blank"
              >
                <i class="bi bi-tiktok"></i>
                TikTok
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
  </div>
</section>
<!-- Courses -->
<section class="bg-light">
  <div class="container p-5">
    <h3 class="text-center text-secondary h1 text-warning" id="learn">
      COURSES
    </h3>
    <div class="row">
      {% for course in courses.items %}
      <div class="col-sm-12 col-md-6 col-lg-4 p-3 d-flex align-items-stretch">
        <a href="{{url_for('courses_bp.course', course_title=course.title)}}" class="text-decoration-none">
          <div class="card bg-dark text-light h-100 w-100">
            <div class="card-body text-center">
              <img
                src="{{url_for('static', filename='course_icons/'+course.icon)}}"
                alt=""
                class="card-img w-25 rounded-circle"
              />
              <h4 class="card-title mb-4">{{course.title}}</h4>
              <p class="card-text">{{course.description}}</p>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
    <!-- more courses -->
    <div class="" style="display: flex; justify-content: flex-end">
      <a href="{{ url_for('courses_bp.courses')}}" class="btn btn-info btn-lg"> More Courses &gt&gt&gt</a>
  </div>
  </div>
</section>
<!-- Lessons -->
<section class="bg-primary">
  <div class="container p-5">
    <div class="row mb-5">
      <div class="col">
        <h3 class="text-uppercase text-center text-light h1">latest lessons</h3>
      </div>
    </div>
    <div class="row">
      {% for lesson in lessons.items %}
      <div class="col-sm-12 col-md-6 col-lg-4 pb-5 d-flex align-items-stretch">

        <a href=""{{url_for('lessons.lesson', lesson_slug=lesson.slug, course=lesson.course_name.title)}}"">
          <div class="card lesson">
            <img
              src="{{url_for('static', filename='lesson_thumbnails/'+lesson.thumbnail)}}"
              class="card-img"
            />
            <div class="card-body d-flex flex-column">
              <h5 class="card-title">
                <a
                  class="text-decoration-none text-dark"
                  href="{{url_for('lessons.lesson', lesson_slug=lesson.slug, course=lesson.course_name.title)}}"
                  >{{lesson.title}}</a
                >
              </h5>
              <p class="card-text mb-0">
                In:
                <a class="text-decoration-none" href="{{ url_for('courses_bp.course', course_title=lesson.course_name.title)}}"
                  >{{lesson.course_name.title}}</a
                >
              </p>
              <span
                ><img
                  class="article-img"
                  src="{{url_for('static', filename='default.png')}}"
                  alt=""
                />By:
                <a href="{{ url_for('users.author', username=lesson.author.username)}}" class="link">{{lesson.author.username}}</a></span
              >
              <span class="text-muted"
                >On: {{lesson.date_posted.strftime('%Y-%m-%d')}}</span
              >
            </div>
        </a>

       
        
        
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

{%endblock%}

pythonic/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
    />
    <link rel="stylesheet" type:"text/css" href="{{ url_for('static',
    filename='main.css') }}" /> {%if title%}
    <title>Arete - {{title}}</title>
    {%else%}
    <title>Arete</title>
    {%endif%}
  </head>
  <body class="d-flex flex-column min-vh-100">
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
      <div class="container">
        <a href="{{url_for('main.home')}}" class="navbar-brand">Arete</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navmenu"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navmenu">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{{url_for('main.about')}}" class="nav-link">About</a>
            </li>
            <li class="nav-item">
              {%if request.path == "/home"%}
              <a href="#learn" class="nav-link active">Start Learning</a>
              {%else%}
              <a href="{{url_for('courses_bp.courses')}}" class="nav-link">Start Learning</a>
              {%endif%}
            </li>
          </ul>
          <!-- User Links -->
          <ul class="navbar-nav ms-auto">
            {%if current_user.is_authenticated%}
            <div class="dropdown show">
              <button class="btn btn-dark bg-dark dropdown-toggle" type="button" id="dropdownMenuButton1"
                  data-bs-toggle="dropdown" aria-expanded="false">
                  My Account
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li class="nav-item">
                      <a href="{{url_for('users.dashboard')}}" class="dropdown-item">Dashboard</a>
                  </li>
                  <li class="nav-item">
                      <a href="{{url_for('users.logout')}}" class="dropdown-item">Logout</a>
                  </li>
              </ul>
          </div>

            {%else%}
            <li class="nav-item">
              <a href="{{url_for('users.register')}}" class="nav-link">Register</a>
            </li>
            <li class="nav-item">
              <a href="{{url_for('users.login')}}" class="nav-link">Login</a>
            </li>
            {%endif%}
          </ul>
        </div>
      </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div class="alert alert-{{category}} text-center">{{message}}</div>
    {% endfor %} {% endif %} {% endwith %} {%block content%} {%endblock%}
    <!-- footer -->
    <footer class="bg-dark mt-auto">
      <div class="container p-3">
        <div class="row text-center text-white">
          <div class="col-md-12 col-lg-4 pb-2">
            <h4 class="text-center text-decoration-underline">Quick Links</h4>
            <ul class="nobull pt-3">
              <li><a href="#" class="link text-white">Privacy Policy</a></li>
              <li>
                <a href="#" class="link text-white">Terms & Conditions</a>
              </li>
            </ul>
          </div>
          <div class="col-md-12 col-lg-4">
            <h4 class="text-center text-decoration-underline pb-3">
              Social Links
            </h4>
            <a href="#" class="text-white p-2"><i class="bi-github"></i></a>
            <a href="#" class="text-white p-2"><i class="bi-youtube"></i></a>
            <a href="#" class="text-white p-2"><i class="bi-facebook"></i></a>
            <a href="#" class="text-white p-2"><i class="bi-twitter"></i></a>
            <a href="#" class="text-white p-2"><i class="bi-instagram"></i></a>
            <a href="#" class="text-white p-2"><i class="bi-tiktok"></i></a>
          </div>
          <div class="col-md-12 col-lg-4 pb-2">
            <h4 class="text-center text-decoration-underline pb-3">
              Contact Us
            </h4>
            <p class="lead">mostafa@arete.com</p>
          </div>
        </div>
        <div class="col text-white text-center position-relative">
          <p class="lead font-weight-bold">Copyright &copy; 2022 | Arete</p>
          <a href="#" class="position-absolute bottom-0 end-0">
            <i class="bi bi-arrow-up-circle h1"></i>
          </a>
        </div>
      </div>
    </footer>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

pythonic/templates/lesson_view.html
{% extends "lesson.html" %}
{% block lesson %}
<div class="container pt-5">
    <br>
    <h2>{{lesson.title}}</h2>
    <hr>
    {{lesson.content | safe}}
</div>

{% endblock lesson %}

pythonic/templates/login.html
{%extends "layout.html"%} {% block content%}
<div class="container my-5 border">
  <form action="" method="POST">
    {{ form.hidden_tag()}}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Log In</legend>

      <div class="form-group">
        {{ form.email.label(class='form-control-label')}} {% if
        form.email.errors%} {{ form.email(class='form-control form-control-lg
        is-invalid')}}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.email(class='form-control form-control-lg')}} {%
        endif %}
      </div>
      <div class="form-group">
        {{ form.password.label(class='form-control-label')}} {% if
        form.password.errors%} {{ form.password(class='form-control
        form-control-lg is-invalid')}}
        <div class="invalid-feedback">
          {% for error in form.password.errors %}
          <span>{{error}}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.password(class='form-control form-control-lg')}} {%
        endif %}
      </div>
      <div class="form-group my-3">
        {{ form.submit(class='btn btn-outline-info')}}
      </div>
      <div class="form-check">
        {{form.remember(class='form-check-input')}}
        {{form.remember.label(class='form-check-input-label')}}
      </div>
    </fieldset>
  </form>
  <small class="text-muted ml-2">
    <a href="#">Forget Password? </a>
  </small>
  <small class="text-muted">
    Need An Account?
    <a class="ml-2" href="{{url_for('users.register')}}"> Sign Up Here</a>
  </small>
</div>
{% endblock content %}